#!/usr/bin/env python3
"""Generate SR Linux startup configs for the Clos fabric from fabric.yml.

This is the miniature of the real pattern: a data model is the source of
truth, device configuration is a rendered artifact, and the renderer is
reviewable in git. Swap fabric.yml for a NetBox API call and the rest of
this script does not change.

Usage:  python3 gen_configs.py
Output: configs/<device>.cfg
"""

import ipaddress
import pathlib
import sys

try:
    import yaml
except ImportError:
    sys.exit("pip install pyyaml")

ROOT = pathlib.Path(__file__).parent
OUT = ROOT / "configs"


def p2p(spine_index: int, leaf_index: int):
    """Return (spine_ip, leaf_ip, prefixlen) for one spine-leaf link."""
    net = ipaddress.ip_network(f"10.0.{spine_index}.{leaf_index * 2}/31")
    hosts = list(net)
    return str(hosts[0]), str(hosts[1]), net.prefixlen


def iface(name, addr, plen):
    return [
        f"set / interface {name} admin-state enable",
        f"set / interface {name} subinterface 0 admin-state enable",
        f"set / interface {name} subinterface 0 ipv4 admin-state enable",
        f"set / interface {name} subinterface 0 ipv4 address {addr}/{plen}",
    ]


def policy():
    """Export anything inside the fabric's own address space, import everything.

    Matching on prefix-set rather than source protocol means a spine
    re-advertising a BGP-learned leaf subnet is covered by the same
    statement as a leaf originating its own connected subnet.
    """
    return [
        "set / routing-policy prefix-set FABRIC prefix 10.255.0.0/16 mask-length-range 32..32",
        "set / routing-policy prefix-set FABRIC prefix 172.16.0.0/12 mask-length-range 24..24",
        "set / routing-policy policy EXPORT-FABRIC statement 10 match prefix-set FABRIC",
        "set / routing-policy policy EXPORT-FABRIC statement 10 action policy-result accept",
        "set / routing-policy policy EXPORT-FABRIC default-action policy-result reject",
        "set / routing-policy policy IMPORT-ALL default-action policy-result accept",
    ]


def bgp(asn, router_id, neighbors):
    """neighbors: list of (peer_ip, peer_asn)."""
    ni = "set / network-instance default protocols bgp"
    lines = [
        f"{ni} admin-state enable",
        f"{ni} autonomous-system {asn}",
        f"{ni} router-id {router_id}",
        f"{ni} afi-safi ipv4-unicast admin-state enable",
        # ECMP across both spines is the whole point of a Clos fabric.
        f"{ni} afi-safi ipv4-unicast multipath allow-multiple-as true",
        f"{ni} afi-safi ipv4-unicast multipath maximum-paths 8",
        f"{ni} group FABRIC admin-state enable",
        f"{ni} group FABRIC export-policy [ EXPORT-FABRIC ]",
        f"{ni} group FABRIC import-policy [ IMPORT-ALL ]",
        f"{ni} group FABRIC afi-safi ipv4-unicast admin-state enable",
        # Fail fast in a lab; tune before you ever suggest these in production.
        f"{ni} group FABRIC timers connect-retry 5",
    ]
    for peer_ip, peer_asn in neighbors:
        lines += [
            f"{ni} neighbor {peer_ip} admin-state enable",
            f"{ni} neighbor {peer_ip} peer-group FABRIC",
            f"{ni} neighbor {peer_ip} peer-as {peer_asn}",
        ]
    return lines


def render(dev, ifaces, subifs, asn, loopback, neighbors):
    lines = [f"# GENERATED by gen_configs.py - do not hand-edit. Device: {dev}"]
    for name, addr, plen in ifaces:
        lines += iface(name, addr, plen)
    lines += iface("system0", loopback, 32)

    lines += [
        "set / network-instance default type default",
        "set / network-instance default admin-state enable",
    ]
    for s in subifs + ["system0.0"]:
        lines.append(f"set / network-instance default interface {s}")

    lines += policy()
    lines += bgp(asn, loopback, neighbors)
    return "\n".join(lines) + "\n"


def main():
    data = yaml.safe_load((ROOT / "fabric.yml").read_text())
    spines, leaves = data["spines"], data["leaves"]
    OUT.mkdir(exist_ok=True)

    for si, sp in enumerate(spines):
        ifaces, subifs, nbrs = [], [], []
        for li, lf in enumerate(leaves):
            s_ip, l_ip, plen = p2p(si, li)
            port = f"ethernet-1/{li + 1}"
            ifaces.append((port, s_ip, plen))
            subifs.append(f"{port}.0")
            nbrs.append((l_ip, lf["asn"]))
        cfg = render(sp["name"], ifaces, subifs, sp["asn"], sp["loopback"], nbrs)
        (OUT / f"{sp['name']}.cfg").write_text(cfg)

    for li, lf in enumerate(leaves):
        ifaces, subifs, nbrs = [], [], []
        for si, sp in enumerate(spines):
            s_ip, l_ip, plen = p2p(si, li)
            port = f"ethernet-1/{si + 1}"
            ifaces.append((port, l_ip, plen))
            subifs.append(f"{port}.0")
            nbrs.append((s_ip, sp["asn"]))
        # Host-facing port: leaf owns .1 of its /24.
        net = ipaddress.ip_network(lf["host_subnet"])
        gw = str(list(net.hosts())[0])
        ifaces.append(("ethernet-1/10", gw, net.prefixlen))
        subifs.append("ethernet-1/10.0")
        cfg = render(lf["name"], ifaces, subifs, lf["asn"], lf["loopback"], nbrs)
        (OUT / f"{lf['name']}.cfg").write_text(cfg)

    print(f"wrote {len(spines) + len(leaves)} configs to {OUT}")


if __name__ == "__main__":
    main()
